In [ ]:
# module
import numpy as np
import pandas as pd
import tqdm
from haversine import haversine
from tqdm import tqdm_pandas, tqdm

In [ ]:
#load data
car = pd.read_csv('car_accident_location.csv')
ped = pd.read_csv('crosswalk_new.csv')

In [ ]:
# 차 사고
car.columns = ['car_lat', 'car_lon']

# 횡단보도
ped_xy = ped[['crosswalk_id', 'lon', 'lat']]
ped_xy.columns = ['crosswalk_id', 'ped_lon', 'ped_lat']

In [ ]:
car['key'] = 0
ped_xy['key'] = 0

C:\Users\abc\anaconda3\envs\please\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
prod = pd.merge(car, ped_xy, on = 'key', how = 'outer')

In [ ]:
lat1 = np.deg2rad(prod['car_lat'])
lat2 = np.deg2rad(prod['ped_lat'])
lon1 = np.deg2rad(prod['car_lon'])
lon2 = np.deg2rad(prod['ped_lon'])
dlat = lat2 - lat1 
dlon = lon2 - lon1 
a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
c = 2 * np.arcsin(np.sqrt(a))

C:\Users\abc\anaconda3\envs\please\lib\site-packages\pandas\core\arraylike.py:364: RuntimeWarning: invalid value encountered in sin
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\abc\anaconda3\envs\please\lib\site-packages\pandas\core\arraylike.py:364: RuntimeWarning: invalid value encountered in cos
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [ ]:
prod['distance'] = c * 6371 * 1000

In [ ]:
prod2 = prod[prod['distance'] <= 100]

In [ ]:
howmany = prod2.groupby('crosswalk_id').count().reset_index().iloc[:, 0:2]

In [ ]:
howmany.columns = ['crosswalk_id', 'count']

In [ ]:
howmany.describe()

             count
count  2394.000000
mean     44.218463
std      85.378371
min       1.000000
25%       8.000000
50%      20.000000
75%      47.000000
max    2387.000000